#!/bin/bash

# This script will run an arosdev container as a "one-off" that will wipe itself when it exits.

EXTRA_OPTS=$@

docker run -i --rm -t -v=/opt/volumes/aros:/home/aros $EXTRA_OPTS arosdev /bin/bash
